spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/master
          jwk-set-uri: http://localhost:8180/auth/realms/master/protocol/openid-connect/certs
logging:
  level:
    org.springframework.security: "DEBUG"